<?php

namespace ContainerQUL8iUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIsValidOwnerValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\IsValidOwnerValidator' shared autowired service.
     *
     * @return \App\Validator\IsValidOwnerValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/IsValidOwnerValidator.php';

        return $container->privates['App\\Validator\\IsValidOwnerValidator'] = new \App\Validator\IsValidOwnerValidator(($container->privates['security.helper'] ?? $container->getSecurity_HelperService()));
    }
}
